export const fields = {
  requestor: {
    required: true,
    type: 'search',
    renderAsTag: true,
    label: 'requestor',
    entity: 'requestor',
    redirectLabel: 'Add New Requestor',
    withRedirect: true,
    urlToRedirect: '/requestor',
    displayLabels: ['firstname', 'lastname'],
    searchFields: 'firstname,lastname',
    dataIndex: ['requestor', 'firstname'],
  },
  events: {
    type: 'search',
    renderAsTag: true,
    label: 'events',
    entity: 'events',
    redirectLabel: 'Add New Event',
    withRedirect: true,
    urlToRedirect: '/events',
    displayLabels: ['name'],
    searchFields: 'name',
    dataIndex: ['events', 'name'],
  },
  name: {
    type: 'string',
    required: true,
  },
  barangay: {
    required: true,
    type: 'selectWithFeedback',
    // renderAsTag: true,
    hasFeedback: true,
    options: [
      { value: 'barangay 1', label: 'barangay 1' },
      { value: 'barangay 2', label: 'barangay 2' },
      { value: 'barangay 3', label: 'barangay 3' },
      { value: 'barangay 4', label: 'barangay 4' },
      { value: 'barangay 5', label: 'barangay 5' },
    ],
  },
  appointmentType: {
    type: 'selectWithFeedback',
    label: 'appointment type',
    renderAsTag: true,
    hasFeedback: true,
    options: [
      { value: 'walk in', label: 'walk in' },
      { value: 'online', label: 'online' },
    ],
    required: true,
  },

  created: {
    type: 'date',
    required: true,
    disableForForm: true,
  },
};
