export const fields = {
  requestor: {
    required: true,
    type: 'search',
    renderAsTag: true,
    label: 'requestor',
    entity: 'requestor',
    redirectLabel: 'Add New Requestor',
    withRedirect: true,
    urlToRedirect: '/requestor',
    displayLabels: ['firstname', 'lastname'],
    searchFields: 'firstname,lastname',
    dataIndex: ['requestor', 'firstname'],
  },
  events: {
    type: 'search',
    renderAsTag: true,
    label: 'events',
    entity: 'events',
    redirectLabel: 'Add New Event',
    withRedirect: true,
    urlToRedirect: '/events',
    displayLabels: ['name'],
    searchFields: 'name',
    dataIndex: ['events', 'name'],
  },
  name: {
    type: 'string',
    required: true,
  },
  created: {
    type: 'date',
    required: true,
    disableForForm: true,
  },
};
